# Generated by Django 2.2 on 2019-04-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_plan_id', models.CharField(blank=True, help_text='Plan Id returned from RazorPay', max_length=20)),
                ('entity_type', models.CharField(blank=True, help_text='Looking at plan response from API - matching to type key', max_length=10)),
                ('plan_name', models.CharField(help_text='Business name of the plan', max_length=300)),
                ('description', models.TextField(help_text='Feature description of the plan')),
                ('amount', models.IntegerField(help_text='Price of the plan')),
                ('currency', models.CharField(default='INR', help_text='Should be INR', max_length=3)),
                ('period', models.CharField(help_text='If customer is charged every 2 months then this value should be monthly', max_length=7)),
                ('interval', models.IntegerField(help_text='If customer is charged every 2 months then this value should be 2')),
                ('notes', models.CharField(blank=True, help_text='This can be converted to a custom object later as key value pairings', max_length=300)),
                ('pub_date', models.DateTimeField(help_text='Time when it was created on admin panel - to be entered', verbose_name='date published')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(help_text='Feature description displayed on plan page', max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
            options={
                'db_table': 'plan_features',
            },
        ),
    ]
