# Generated by Django 2.2 on 2019-04-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190416_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
