# Generated by Django 2.2 on 2019-04-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20190416_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(help_text='Price of the plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(help_text='Should be INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.IntegerField(help_text='If customer is charged every 2 months then this value should be 2'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(help_text='If customer is charged every 2 months then this value should be monthly', max_length=7),
        ),
    ]
