# Generated by Django 2.2 on 2019-06-06 14:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190604_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Phone added on', verbose_name='date created')),
                ('modified_at', models.DateTimeField(auto_now_add=True, help_text='Phone last updated on', verbose_name='date modified')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
    ]
