# Generated by Django 2.2 on 2019-06-07 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190606_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserPhone', to_field='phone_no'),
        ),
        migrations.AddField(
            model_name='userphone',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
