# Generated by Django 2.2 on 2019-07-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190715_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='code',
            field=models.IntegerField(help_text='This is sent to user on his email entry', null=True),
        ),
    ]
