# Generated by Django 2.2 on 2019-07-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_guestemail_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestemail',
            old_name='modified_at',
            new_name='created_at',
        ),
    ]
