# Generated by Django 2.2 on 2019-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Time when this is modified on admin panel - to be entered', verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(default=99, help_text='Price of the plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when it was created on admin panel'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.IntegerField(default=1, help_text='If customer is charged every 2 months then this value should be 2'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(default='monthly', help_text='If customer is charged every 2 months then this value should be monthly', max_length=2),
        ),
    ]
