# Generated by Django 2.2 on 2019-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20190416_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(default='monthly', help_text='If customer is charged every 2 months then this value should be monthly', max_length=7),
        ),
    ]
